// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class AlertConfig {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AlertConfig {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAlertConfig(bb:flatbuffers.ByteBuffer, obj?:AlertConfig):AlertConfig {
  return (obj || new AlertConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAlertConfig(bb:flatbuffers.ByteBuffer, obj?:AlertConfig):AlertConfig {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AlertConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

alertId():string|null
alertId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
alertId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

symbol():string|null
symbol(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
symbol(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

conditionType():string|null
conditionType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
conditionType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

threshold():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startAlertConfig(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addAlertId(builder:flatbuffers.Builder, alertIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, alertIdOffset, 0);
}

static addSymbol(builder:flatbuffers.Builder, symbolOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, symbolOffset, 0);
}

static addConditionType(builder:flatbuffers.Builder, conditionTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, conditionTypeOffset, 0);
}

static addThreshold(builder:flatbuffers.Builder, threshold:number) {
  builder.addFieldFloat64(3, threshold, 0.0);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(4, +active, +false);
}

static endAlertConfig(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAlertConfig(builder:flatbuffers.Builder, alertIdOffset:flatbuffers.Offset, symbolOffset:flatbuffers.Offset, conditionTypeOffset:flatbuffers.Offset, threshold:number, active:boolean):flatbuffers.Offset {
  AlertConfig.startAlertConfig(builder);
  AlertConfig.addAlertId(builder, alertIdOffset);
  AlertConfig.addSymbol(builder, symbolOffset);
  AlertConfig.addConditionType(builder, conditionTypeOffset);
  AlertConfig.addThreshold(builder, threshold);
  AlertConfig.addActive(builder, active);
  return AlertConfig.endAlertConfig(builder);
}
}
