// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Candle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Candle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCandle(bb:flatbuffers.ByteBuffer, obj?:Candle):Candle {
  return (obj || new Candle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCandle(bb:flatbuffers.ByteBuffer, obj?:Candle):Candle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Candle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

symbol():string|null
symbol(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
symbol(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

open():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

high():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

low():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

close():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

volume():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

vwap():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startCandle(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addSymbol(builder:flatbuffers.Builder, symbolOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, symbolOffset, 0);
}

static addOpen(builder:flatbuffers.Builder, open:number) {
  builder.addFieldFloat64(2, open, 0.0);
}

static addHigh(builder:flatbuffers.Builder, high:number) {
  builder.addFieldFloat64(3, high, 0.0);
}

static addLow(builder:flatbuffers.Builder, low:number) {
  builder.addFieldFloat64(4, low, 0.0);
}

static addClose(builder:flatbuffers.Builder, close:number) {
  builder.addFieldFloat64(5, close, 0.0);
}

static addVolume(builder:flatbuffers.Builder, volume:number) {
  builder.addFieldFloat64(6, volume, 0.0);
}

static addVwap(builder:flatbuffers.Builder, vwap:number) {
  builder.addFieldFloat64(7, vwap, 0.0);
}

static endCandle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCandle(builder:flatbuffers.Builder, timestamp:bigint, symbolOffset:flatbuffers.Offset, open:number, high:number, low:number, close:number, volume:number, vwap:number):flatbuffers.Offset {
  Candle.startCandle(builder);
  Candle.addTimestamp(builder, timestamp);
  Candle.addSymbol(builder, symbolOffset);
  Candle.addOpen(builder, open);
  Candle.addHigh(builder, high);
  Candle.addLow(builder, low);
  Candle.addClose(builder, close);
  Candle.addVolume(builder, volume);
  Candle.addVwap(builder, vwap);
  return Candle.endCandle(builder);
}
}
