// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Color {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Color {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

r():number {
  return this.bb!.readUint8(this.bb_pos);
}

g():number {
  return this.bb!.readUint8(this.bb_pos + 1);
}

b():number {
  return this.bb!.readUint8(this.bb_pos + 2);
}

a():number {
  return this.bb!.readUint8(this.bb_pos + 3);
}

static sizeOf():number {
  return 4;
}

static createColor(builder:flatbuffers.Builder, r: number, g: number, b: number, a: number):flatbuffers.Offset {
  builder.prep(1, 4);
  builder.writeInt8(a);
  builder.writeInt8(b);
  builder.writeInt8(g);
  builder.writeInt8(r);
  return builder.offset();
}

}
