// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Color } from '../../nexus-quant/protocol/color.js';
import { Point } from '../../nexus-quant/protocol/point.js';


export class DrawingPolygon {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DrawingPolygon {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDrawingPolygon(bb:flatbuffers.ByteBuffer, obj?:DrawingPolygon):DrawingPolygon {
  return (obj || new DrawingPolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDrawingPolygon(bb:flatbuffers.ByteBuffer, obj?:DrawingPolygon):DrawingPolygon {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DrawingPolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

points(index: number, obj?:Point):Point|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Point()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 16, this.bb!) : null;
}

pointsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

color(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

fill():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startDrawingPolygon(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPoints(builder:flatbuffers.Builder, pointsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, pointsOffset, 0);
}

static startPointsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(16, numElems, 8);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, colorOffset, 0);
}

static addFill(builder:flatbuffers.Builder, fill:boolean) {
  builder.addFieldInt8(2, +fill, +false);
}

static endDrawingPolygon(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
