// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Color } from '../../nexus-quant/protocol/color';


export class DrawingRect {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DrawingRect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDrawingRect(bb:flatbuffers.ByteBuffer, obj?:DrawingRect):DrawingRect {
  return (obj || new DrawingRect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDrawingRect(bb:flatbuffers.ByteBuffer, obj?:DrawingRect):DrawingRect {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DrawingRect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

x1():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

y1():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

x2():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

y2():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

color(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

fill():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startDrawingRect(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addX1(builder:flatbuffers.Builder, x1:number) {
  builder.addFieldFloat64(0, x1, 0.0);
}

static addY1(builder:flatbuffers.Builder, y1:number) {
  builder.addFieldFloat64(1, y1, 0.0);
}

static addX2(builder:flatbuffers.Builder, x2:number) {
  builder.addFieldFloat64(2, x2, 0.0);
}

static addY2(builder:flatbuffers.Builder, y2:number) {
  builder.addFieldFloat64(3, y2, 0.0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, colorOffset, 0);
}

static addFill(builder:flatbuffers.Builder, fill:boolean) {
  builder.addFieldInt8(5, +fill, +false);
}

static endDrawingRect(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
