// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Color } from '../../nexus-quant/protocol/color';
import { Point } from '../../nexus-quant/protocol/point';


export class DrawingLine {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DrawingLine {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDrawingLine(bb:flatbuffers.ByteBuffer, obj?:DrawingLine):DrawingLine {
  return (obj || new DrawingLine()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDrawingLine(bb:flatbuffers.ByteBuffer, obj?:DrawingLine):DrawingLine {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DrawingLine()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

start(obj?:Point):Point|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Point()).__init(this.bb_pos + offset, this.bb!) : null;
}

end(obj?:Point):Point|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Point()).__init(this.bb_pos + offset, this.bb!) : null;
}

color(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startDrawingLine(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addStart(builder:flatbuffers.Builder, startOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, startOffset, 0);
}

static addEnd(builder:flatbuffers.Builder, endOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, endOffset, 0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, colorOffset, 0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldFloat32(3, width, 0.0);
}

static endDrawingLine(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
