// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DrawingLine } from '../../nexus-quant/protocol/drawing-line.js';
import { DrawingPolygon } from '../../nexus-quant/protocol/drawing-polygon.js';
import { DrawingRect } from '../../nexus-quant/protocol/drawing-rect.js';
import { DrawingText } from '../../nexus-quant/protocol/drawing-text.js';
import { IndicatorValue } from '../../nexus-quant/protocol/indicator-value.js';


export class IndicatorPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IndicatorPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsIndicatorPayload(bb:flatbuffers.ByteBuffer, obj?:IndicatorPayload):IndicatorPayload {
  return (obj || new IndicatorPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsIndicatorPayload(bb:flatbuffers.ByteBuffer, obj?:IndicatorPayload):IndicatorPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new IndicatorPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

indicatorId():string|null
indicatorId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
indicatorId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

values(index: number, obj?:IndicatorValue):IndicatorValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new IndicatorValue()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

valuesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

lines(index: number, obj?:DrawingLine):DrawingLine|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new DrawingLine()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

linesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

rectangles(index: number, obj?:DrawingRect):DrawingRect|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new DrawingRect()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

rectanglesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

polygons(index: number, obj?:DrawingPolygon):DrawingPolygon|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new DrawingPolygon()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

polygonsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

texts(index: number, obj?:DrawingText):DrawingText|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new DrawingText()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

textsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startIndicatorPayload(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addIndicatorId(builder:flatbuffers.Builder, indicatorIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, indicatorIdOffset, 0);
}

static addValues(builder:flatbuffers.Builder, valuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valuesOffset, 0);
}

static createValuesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startValuesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLines(builder:flatbuffers.Builder, linesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, linesOffset, 0);
}

static createLinesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLinesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRectangles(builder:flatbuffers.Builder, rectanglesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, rectanglesOffset, 0);
}

static createRectanglesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRectanglesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addPolygons(builder:flatbuffers.Builder, polygonsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, polygonsOffset, 0);
}

static createPolygonsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPolygonsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTexts(builder:flatbuffers.Builder, textsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, textsOffset, 0);
}

static createTextsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTextsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endIndicatorPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishIndicatorPayloadBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedIndicatorPayloadBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createIndicatorPayload(builder:flatbuffers.Builder, indicatorIdOffset:flatbuffers.Offset, valuesOffset:flatbuffers.Offset, linesOffset:flatbuffers.Offset, rectanglesOffset:flatbuffers.Offset, polygonsOffset:flatbuffers.Offset, textsOffset:flatbuffers.Offset):flatbuffers.Offset {
  IndicatorPayload.startIndicatorPayload(builder);
  IndicatorPayload.addIndicatorId(builder, indicatorIdOffset);
  IndicatorPayload.addValues(builder, valuesOffset);
  IndicatorPayload.addLines(builder, linesOffset);
  IndicatorPayload.addRectangles(builder, rectanglesOffset);
  IndicatorPayload.addPolygons(builder, polygonsOffset);
  IndicatorPayload.addTexts(builder, textsOffset);
  return IndicatorPayload.endIndicatorPayload(builder);
}
}
