// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Candle } from '../../nexus-quant/protocol/candle.js';
import { Tick } from '../../nexus-quant/protocol/tick.js';


export class MarketDataBatch {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MarketDataBatch {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMarketDataBatch(bb:flatbuffers.ByteBuffer, obj?:MarketDataBatch):MarketDataBatch {
  return (obj || new MarketDataBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMarketDataBatch(bb:flatbuffers.ByteBuffer, obj?:MarketDataBatch):MarketDataBatch {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MarketDataBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ticks(index: number, obj?:Tick):Tick|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Tick()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

ticksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

candles(index: number, obj?:Candle):Candle|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Candle()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

candlesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMarketDataBatch(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTicks(builder:flatbuffers.Builder, ticksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, ticksOffset, 0);
}

static createTicksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTicksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCandles(builder:flatbuffers.Builder, candlesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, candlesOffset, 0);
}

static createCandlesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCandlesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMarketDataBatch(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishMarketDataBatchBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedMarketDataBatchBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createMarketDataBatch(builder:flatbuffers.Builder, ticksOffset:flatbuffers.Offset, candlesOffset:flatbuffers.Offset):flatbuffers.Offset {
  MarketDataBatch.startMarketDataBatch(builder);
  MarketDataBatch.addTicks(builder, ticksOffset);
  MarketDataBatch.addCandles(builder, candlesOffset);
  return MarketDataBatch.endMarketDataBatch(builder);
}
}
