// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ReplayConfig {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReplayConfig {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReplayConfig(bb:flatbuffers.ByteBuffer, obj?:ReplayConfig):ReplayConfig {
  return (obj || new ReplayConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReplayConfig(bb:flatbuffers.ByteBuffer, obj?:ReplayConfig):ReplayConfig {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReplayConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

symbol():string|null
symbol(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
symbol(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

startTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

endTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

speed():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startReplayConfig(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addSymbol(builder:flatbuffers.Builder, symbolOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, symbolOffset, 0);
}

static addStartTime(builder:flatbuffers.Builder, startTime:bigint) {
  builder.addFieldInt64(1, startTime, BigInt('0'));
}

static addEndTime(builder:flatbuffers.Builder, endTime:bigint) {
  builder.addFieldInt64(2, endTime, BigInt('0'));
}

static addSpeed(builder:flatbuffers.Builder, speed:number) {
  builder.addFieldFloat32(3, speed, 0.0);
}

static endReplayConfig(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createReplayConfig(builder:flatbuffers.Builder, symbolOffset:flatbuffers.Offset, startTime:bigint, endTime:bigint, speed:number):flatbuffers.Offset {
  ReplayConfig.startReplayConfig(builder);
  ReplayConfig.addSymbol(builder, symbolOffset);
  ReplayConfig.addStartTime(builder, startTime);
  ReplayConfig.addEndTime(builder, endTime);
  ReplayConfig.addSpeed(builder, speed);
  return ReplayConfig.endReplayConfig(builder);
}
}
