// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AlertConfig } from '../../nexus-quant/protocol/alert-config.js';
import { CommandType } from '../../nexus-quant/protocol/command-type.js';
import { ReplayConfig } from '../../nexus-quant/protocol/replay-config.js';
import { SubscriptionPayload } from '../../nexus-quant/protocol/subscription-payload.js';


export class RPCRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RPCRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRPCRequest(bb:flatbuffers.ByteBuffer, obj?:RPCRequest):RPCRequest {
  return (obj || new RPCRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRPCRequest(bb:flatbuffers.ByteBuffer, obj?:RPCRequest):RPCRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RPCRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestId():string|null
requestId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
requestId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

command():CommandType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : CommandType.Subscribe;
}

symbol():string|null
symbol(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
symbol(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

replayConfig(obj?:ReplayConfig):ReplayConfig|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ReplayConfig()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

subscription(obj?:SubscriptionPayload):SubscriptionPayload|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new SubscriptionPayload()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

alertConfig(obj?:AlertConfig):AlertConfig|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new AlertConfig()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

seekTimestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

speedMultiplier():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startRPCRequest(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addRequestId(builder:flatbuffers.Builder, requestIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, requestIdOffset, 0);
}

static addCommand(builder:flatbuffers.Builder, command:CommandType) {
  builder.addFieldInt8(1, command, CommandType.Subscribe);
}

static addSymbol(builder:flatbuffers.Builder, symbolOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, symbolOffset, 0);
}

static addReplayConfig(builder:flatbuffers.Builder, replayConfigOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, replayConfigOffset, 0);
}

static addSubscription(builder:flatbuffers.Builder, subscriptionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, subscriptionOffset, 0);
}

static addAlertConfig(builder:flatbuffers.Builder, alertConfigOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, alertConfigOffset, 0);
}

static addSeekTimestamp(builder:flatbuffers.Builder, seekTimestamp:bigint) {
  builder.addFieldInt64(6, seekTimestamp, BigInt('0'));
}

static addSpeedMultiplier(builder:flatbuffers.Builder, speedMultiplier:number) {
  builder.addFieldFloat32(7, speedMultiplier, 0.0);
}

static endRPCRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishRPCRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedRPCRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

}
