// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class RPCResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RPCResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRPCResponse(bb:flatbuffers.ByteBuffer, obj?:RPCResponse):RPCResponse {
  return (obj || new RPCResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRPCResponse(bb:flatbuffers.ByteBuffer, obj?:RPCResponse):RPCResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RPCResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestId():string|null
requestId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
requestId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

success():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

errorMessage():string|null
errorMessage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
errorMessage(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startRPCResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addRequestId(builder:flatbuffers.Builder, requestIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, requestIdOffset, 0);
}

static addSuccess(builder:flatbuffers.Builder, success:boolean) {
  builder.addFieldInt8(1, +success, +false);
}

static addErrorMessage(builder:flatbuffers.Builder, errorMessageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, errorMessageOffset, 0);
}

static endRPCResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRPCResponse(builder:flatbuffers.Builder, requestIdOffset:flatbuffers.Offset, success:boolean, errorMessageOffset:flatbuffers.Offset):flatbuffers.Offset {
  RPCResponse.startRPCResponse(builder);
  RPCResponse.addRequestId(builder, requestIdOffset);
  RPCResponse.addSuccess(builder, success);
  RPCResponse.addErrorMessage(builder, errorMessageOffset);
  return RPCResponse.endRPCResponse(builder);
}
}
