// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class SubscriptionPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SubscriptionPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSubscriptionPayload(bb:flatbuffers.ByteBuffer, obj?:SubscriptionPayload):SubscriptionPayload {
  return (obj || new SubscriptionPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSubscriptionPayload(bb:flatbuffers.ByteBuffer, obj?:SubscriptionPayload):SubscriptionPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SubscriptionPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

symbols(index: number):string
symbols(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
symbols(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

symbolsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSubscriptionPayload(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSymbols(builder:flatbuffers.Builder, symbolsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, symbolsOffset, 0);
}

static createSymbolsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSymbolsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSubscriptionPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSubscriptionPayload(builder:flatbuffers.Builder, symbolsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SubscriptionPayload.startSubscriptionPayload(builder);
  SubscriptionPayload.addSymbols(builder, symbolsOffset);
  return SubscriptionPayload.endSubscriptionPayload(builder);
}
}
