// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Tick {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Tick {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTick(bb:flatbuffers.ByteBuffer, obj?:Tick):Tick {
  return (obj || new Tick()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTick(bb:flatbuffers.ByteBuffer, obj?:Tick):Tick {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Tick()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

symbol():string|null
symbol(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
symbol(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

price():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

volume():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

bid():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

ask():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

bidSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

askSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startTick(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addSymbol(builder:flatbuffers.Builder, symbolOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, symbolOffset, 0);
}

static addPrice(builder:flatbuffers.Builder, price:number) {
  builder.addFieldFloat64(2, price, 0.0);
}

static addVolume(builder:flatbuffers.Builder, volume:number) {
  builder.addFieldFloat64(3, volume, 0.0);
}

static addBid(builder:flatbuffers.Builder, bid:number) {
  builder.addFieldFloat64(4, bid, 0.0);
}

static addAsk(builder:flatbuffers.Builder, ask:number) {
  builder.addFieldFloat64(5, ask, 0.0);
}

static addBidSize(builder:flatbuffers.Builder, bidSize:number) {
  builder.addFieldFloat64(6, bidSize, 0.0);
}

static addAskSize(builder:flatbuffers.Builder, askSize:number) {
  builder.addFieldFloat64(7, askSize, 0.0);
}

static endTick(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTick(builder:flatbuffers.Builder, timestamp:bigint, symbolOffset:flatbuffers.Offset, price:number, volume:number, bid:number, ask:number, bidSize:number, askSize:number):flatbuffers.Offset {
  Tick.startTick(builder);
  Tick.addTimestamp(builder, timestamp);
  Tick.addSymbol(builder, symbolOffset);
  Tick.addPrice(builder, price);
  Tick.addVolume(builder, volume);
  Tick.addBid(builder, bid);
  Tick.addAsk(builder, ask);
  Tick.addBidSize(builder, bidSize);
  Tick.addAskSize(builder, askSize);
  return Tick.endTick(builder);
}
}
