# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AlertConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AlertConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAlertConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AlertConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AlertConfig
    def AlertId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AlertConfig
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AlertConfig
    def ConditionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AlertConfig
    def Threshold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # AlertConfig
    def Active(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def AlertConfigStart(builder):
    builder.StartObject(5)

def Start(builder):
    AlertConfigStart(builder)

def AlertConfigAddAlertId(builder, alertId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(alertId), 0)

def AddAlertId(builder, alertId):
    AlertConfigAddAlertId(builder, alertId)

def AlertConfigAddSymbol(builder, symbol):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)

def AddSymbol(builder, symbol):
    AlertConfigAddSymbol(builder, symbol)

def AlertConfigAddConditionType(builder, conditionType):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(conditionType), 0)

def AddConditionType(builder, conditionType):
    AlertConfigAddConditionType(builder, conditionType)

def AlertConfigAddThreshold(builder, threshold):
    builder.PrependFloat64Slot(3, threshold, 0.0)

def AddThreshold(builder, threshold):
    AlertConfigAddThreshold(builder, threshold)

def AlertConfigAddActive(builder, active):
    builder.PrependBoolSlot(4, active, 0)

def AddActive(builder, active):
    AlertConfigAddActive(builder, active)

def AlertConfigEnd(builder):
    return builder.EndObject()

def End(builder):
    return AlertConfigEnd(builder)
