# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Candle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Candle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCandle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Candle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Candle
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Candle
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Candle
    def Open(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Candle
    def High(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Candle
    def Low(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Candle
    def Close(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Candle
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Candle
    def Vwap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def CandleStart(builder):
    builder.StartObject(8)

def Start(builder):
    CandleStart(builder)

def CandleAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    CandleAddTimestamp(builder, timestamp)

def CandleAddSymbol(builder, symbol):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)

def AddSymbol(builder, symbol):
    CandleAddSymbol(builder, symbol)

def CandleAddOpen(builder, open):
    builder.PrependFloat64Slot(2, open, 0.0)

def AddOpen(builder, open):
    CandleAddOpen(builder, open)

def CandleAddHigh(builder, high):
    builder.PrependFloat64Slot(3, high, 0.0)

def AddHigh(builder, high):
    CandleAddHigh(builder, high)

def CandleAddLow(builder, low):
    builder.PrependFloat64Slot(4, low, 0.0)

def AddLow(builder, low):
    CandleAddLow(builder, low)

def CandleAddClose(builder, close):
    builder.PrependFloat64Slot(5, close, 0.0)

def AddClose(builder, close):
    CandleAddClose(builder, close)

def CandleAddVolume(builder, volume):
    builder.PrependFloat64Slot(6, volume, 0.0)

def AddVolume(builder, volume):
    CandleAddVolume(builder, volume)

def CandleAddVwap(builder, vwap):
    builder.PrependFloat64Slot(7, vwap, 0.0)

def AddVwap(builder, vwap):
    CandleAddVwap(builder, vwap)

def CandleEnd(builder):
    return builder.EndObject()

def End(builder):
    return CandleEnd(builder)
