# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

class CommandType(object):
    Subscribe = 0
    Unsubscribe = 1
    ReplayStart = 2
    ReplayPause = 3
    ReplayStop = 4
    ReplaySeek = 5
    ReplaySpeed = 6
    RegisterAlert = 7
    TriggerAlert = 8
