# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DrawingPolygon(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DrawingPolygon()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDrawingPolygon(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DrawingPolygon
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DrawingPolygon
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from NexusQuant.Protocol.Point import Point
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DrawingPolygon
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DrawingPolygon
    def PointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # DrawingPolygon
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from NexusQuant.Protocol.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DrawingPolygon
    def Fill(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def DrawingPolygonStart(builder):
    builder.StartObject(3)

def Start(builder):
    DrawingPolygonStart(builder)

def DrawingPolygonAddPoints(builder, points):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)

def AddPoints(builder, points):
    DrawingPolygonAddPoints(builder, points)

def DrawingPolygonStartPointsVector(builder, numElems):
    return builder.StartVector(16, numElems, 8)

def StartPointsVector(builder, numElems):
    return DrawingPolygonStartPointsVector(builder, numElems)

def DrawingPolygonAddColor(builder, color):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)

def AddColor(builder, color):
    DrawingPolygonAddColor(builder, color)

def DrawingPolygonAddFill(builder, fill):
    builder.PrependBoolSlot(2, fill, 0)

def AddFill(builder, fill):
    DrawingPolygonAddFill(builder, fill)

def DrawingPolygonEnd(builder):
    return builder.EndObject()

def End(builder):
    return DrawingPolygonEnd(builder)
