# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DrawingText(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DrawingText()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDrawingText(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DrawingText
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DrawingText
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DrawingText
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DrawingText
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DrawingText
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from NexusQuant.Protocol.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DrawingText
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def DrawingTextStart(builder):
    builder.StartObject(5)

def Start(builder):
    DrawingTextStart(builder)

def DrawingTextAddX(builder, x):
    builder.PrependFloat64Slot(0, x, 0.0)

def AddX(builder, x):
    DrawingTextAddX(builder, x)

def DrawingTextAddY(builder, y):
    builder.PrependFloat64Slot(1, y, 0.0)

def AddY(builder, y):
    DrawingTextAddY(builder, y)

def DrawingTextAddText(builder, text):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)

def AddText(builder, text):
    DrawingTextAddText(builder, text)

def DrawingTextAddColor(builder, color):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)

def AddColor(builder, color):
    DrawingTextAddColor(builder, color)

def DrawingTextAddSize(builder, size):
    builder.PrependFloat32Slot(4, size, 0.0)

def AddSize(builder, size):
    DrawingTextAddSize(builder, size)

def DrawingTextEnd(builder):
    return builder.EndObject()

def End(builder):
    return DrawingTextEnd(builder)
