# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DrawingLine(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DrawingLine()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDrawingLine(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DrawingLine
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DrawingLine
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from NexusQuant.Protocol.Point import Point
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DrawingLine
    def End(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from NexusQuant.Protocol.Point import Point
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DrawingLine
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from NexusQuant.Protocol.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DrawingLine
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def DrawingLineStart(builder):
    builder.StartObject(4)

def Start(builder):
    DrawingLineStart(builder)

def DrawingLineAddStart(builder, start):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(start), 0)

def AddStart(builder, start):
    DrawingLineAddStart(builder, start)

def DrawingLineAddEnd(builder, end):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(end), 0)

def AddEnd(builder, end):
    DrawingLineAddEnd(builder, end)

def DrawingLineAddColor(builder, color):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)

def AddColor(builder, color):
    DrawingLineAddColor(builder, color)

def DrawingLineAddWidth(builder, width):
    builder.PrependFloat32Slot(3, width, 0.0)

def AddWidth(builder, width):
    DrawingLineAddWidth(builder, width)

def DrawingLineEnd(builder):
    return builder.EndObject()

def End(builder):
    return DrawingLineEnd(builder)
