# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DrawingRect(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DrawingRect()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDrawingRect(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DrawingRect
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DrawingRect
    def X1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DrawingRect
    def Y1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DrawingRect
    def X2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DrawingRect
    def Y2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DrawingRect
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from NexusQuant.Protocol.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DrawingRect
    def Fill(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def DrawingRectStart(builder): builder.StartObject(6)
def Start(builder):
    return DrawingRectStart(builder)
def DrawingRectAddX1(builder, x1): builder.PrependFloat64Slot(0, x1, 0.0)
def AddX1(builder, x1):
    return DrawingRectAddX1(builder, x1)
def DrawingRectAddY1(builder, y1): builder.PrependFloat64Slot(1, y1, 0.0)
def AddY1(builder, y1):
    return DrawingRectAddY1(builder, y1)
def DrawingRectAddX2(builder, x2): builder.PrependFloat64Slot(2, x2, 0.0)
def AddX2(builder, x2):
    return DrawingRectAddX2(builder, x2)
def DrawingRectAddY2(builder, y2): builder.PrependFloat64Slot(3, y2, 0.0)
def AddY2(builder, y2):
    return DrawingRectAddY2(builder, y2)
def DrawingRectAddColor(builder, color): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)
def AddColor(builder, color):
    return DrawingRectAddColor(builder, color)
def DrawingRectAddFill(builder, fill): builder.PrependBoolSlot(5, fill, 0)
def AddFill(builder, fill):
    return DrawingRectAddFill(builder, fill)
def DrawingRectEnd(builder): return builder.EndObject()
def End(builder):
    return DrawingRectEnd(builder)