# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IndicatorPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IndicatorPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIndicatorPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IndicatorPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IndicatorPayload
    def IndicatorId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IndicatorPayload
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NexusQuant.Protocol.IndicatorValue import IndicatorValue
            obj = IndicatorValue()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IndicatorPayload
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndicatorPayload
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # IndicatorPayload
    def Lines(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NexusQuant.Protocol.DrawingLine import DrawingLine
            obj = DrawingLine()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IndicatorPayload
    def LinesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndicatorPayload
    def LinesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # IndicatorPayload
    def Rectangles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NexusQuant.Protocol.DrawingRect import DrawingRect
            obj = DrawingRect()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IndicatorPayload
    def RectanglesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndicatorPayload
    def RectanglesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # IndicatorPayload
    def Polygons(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NexusQuant.Protocol.DrawingPolygon import DrawingPolygon
            obj = DrawingPolygon()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IndicatorPayload
    def PolygonsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndicatorPayload
    def PolygonsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # IndicatorPayload
    def Texts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NexusQuant.Protocol.DrawingText import DrawingText
            obj = DrawingText()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IndicatorPayload
    def TextsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndicatorPayload
    def TextsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def IndicatorPayloadStart(builder): builder.StartObject(6)
def Start(builder):
    return IndicatorPayloadStart(builder)
def IndicatorPayloadAddIndicatorId(builder, indicatorId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorId), 0)
def AddIndicatorId(builder, indicatorId):
    return IndicatorPayloadAddIndicatorId(builder, indicatorId)
def IndicatorPayloadAddValues(builder, values): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)
def AddValues(builder, values):
    return IndicatorPayloadAddValues(builder, values)
def IndicatorPayloadStartValuesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartValuesVector(builder, numElems):
    return IndicatorPayloadStartValuesVector(builder, numElems)
def IndicatorPayloadAddLines(builder, lines): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(lines), 0)
def AddLines(builder, lines):
    return IndicatorPayloadAddLines(builder, lines)
def IndicatorPayloadStartLinesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartLinesVector(builder, numElems):
    return IndicatorPayloadStartLinesVector(builder, numElems)
def IndicatorPayloadAddRectangles(builder, rectangles): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(rectangles), 0)
def AddRectangles(builder, rectangles):
    return IndicatorPayloadAddRectangles(builder, rectangles)
def IndicatorPayloadStartRectanglesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartRectanglesVector(builder, numElems):
    return IndicatorPayloadStartRectanglesVector(builder, numElems)
def IndicatorPayloadAddPolygons(builder, polygons): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(polygons), 0)
def AddPolygons(builder, polygons):
    return IndicatorPayloadAddPolygons(builder, polygons)
def IndicatorPayloadStartPolygonsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartPolygonsVector(builder, numElems):
    return IndicatorPayloadStartPolygonsVector(builder, numElems)
def IndicatorPayloadAddTexts(builder, texts): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(texts), 0)
def AddTexts(builder, texts):
    return IndicatorPayloadAddTexts(builder, texts)
def IndicatorPayloadStartTextsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartTextsVector(builder, numElems):
    return IndicatorPayloadStartTextsVector(builder, numElems)
def IndicatorPayloadEnd(builder): return builder.EndObject()
def End(builder):
    return IndicatorPayloadEnd(builder)