# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MarketDataBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MarketDataBatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMarketDataBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MarketDataBatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MarketDataBatch
    def Ticks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NexusQuant.Protocol.Tick import Tick
            obj = Tick()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MarketDataBatch
    def TicksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MarketDataBatch
    def TicksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # MarketDataBatch
    def Candles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NexusQuant.Protocol.Candle import Candle
            obj = Candle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MarketDataBatch
    def CandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MarketDataBatch
    def CandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def MarketDataBatchStart(builder):
    builder.StartObject(2)

def Start(builder):
    MarketDataBatchStart(builder)

def MarketDataBatchAddTicks(builder, ticks):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ticks), 0)

def AddTicks(builder, ticks):
    MarketDataBatchAddTicks(builder, ticks)

def MarketDataBatchStartTicksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTicksVector(builder, numElems):
    return MarketDataBatchStartTicksVector(builder, numElems)

def MarketDataBatchAddCandles(builder, candles):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(candles), 0)

def AddCandles(builder, candles):
    MarketDataBatchAddCandles(builder, candles)

def MarketDataBatchStartCandlesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCandlesVector(builder, numElems):
    return MarketDataBatchStartCandlesVector(builder, numElems)

def MarketDataBatchEnd(builder):
    return builder.EndObject()

def End(builder):
    return MarketDataBatchEnd(builder)
