# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReplayConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReplayConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReplayConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReplayConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReplayConfig
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReplayConfig
    def StartTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ReplayConfig
    def EndTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ReplayConfig
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ReplayConfigStart(builder):
    builder.StartObject(4)

def Start(builder):
    ReplayConfigStart(builder)

def ReplayConfigAddSymbol(builder, symbol):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)

def AddSymbol(builder, symbol):
    ReplayConfigAddSymbol(builder, symbol)

def ReplayConfigAddStartTime(builder, startTime):
    builder.PrependInt64Slot(1, startTime, 0)

def AddStartTime(builder, startTime):
    ReplayConfigAddStartTime(builder, startTime)

def ReplayConfigAddEndTime(builder, endTime):
    builder.PrependInt64Slot(2, endTime, 0)

def AddEndTime(builder, endTime):
    ReplayConfigAddEndTime(builder, endTime)

def ReplayConfigAddSpeed(builder, speed):
    builder.PrependFloat32Slot(3, speed, 0.0)

def AddSpeed(builder, speed):
    ReplayConfigAddSpeed(builder, speed)

def ReplayConfigEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReplayConfigEnd(builder)
