# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RPCRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RPCRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRPCRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RPCRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RPCRequest
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RPCRequest
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # RPCRequest
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RPCRequest
    def ReplayConfig(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from NexusQuant.Protocol.ReplayConfig import ReplayConfig
            obj = ReplayConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RPCRequest
    def Subscription(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from NexusQuant.Protocol.SubscriptionPayload import SubscriptionPayload
            obj = SubscriptionPayload()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RPCRequest
    def AlertConfig(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from NexusQuant.Protocol.AlertConfig import AlertConfig
            obj = AlertConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RPCRequest
    def SeekTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # RPCRequest
    def SpeedMultiplier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def RPCRequestStart(builder): builder.StartObject(8)
def Start(builder):
    return RPCRequestStart(builder)
def RPCRequestAddRequestId(builder, requestId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)
def AddRequestId(builder, requestId):
    return RPCRequestAddRequestId(builder, requestId)
def RPCRequestAddCommand(builder, command): builder.PrependInt8Slot(1, command, 0)
def AddCommand(builder, command):
    return RPCRequestAddCommand(builder, command)
def RPCRequestAddSymbol(builder, symbol): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)
def AddSymbol(builder, symbol):
    return RPCRequestAddSymbol(builder, symbol)
def RPCRequestAddReplayConfig(builder, replayConfig): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(replayConfig), 0)
def AddReplayConfig(builder, replayConfig):
    return RPCRequestAddReplayConfig(builder, replayConfig)
def RPCRequestAddSubscription(builder, subscription): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(subscription), 0)
def AddSubscription(builder, subscription):
    return RPCRequestAddSubscription(builder, subscription)
def RPCRequestAddAlertConfig(builder, alertConfig): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(alertConfig), 0)
def AddAlertConfig(builder, alertConfig):
    return RPCRequestAddAlertConfig(builder, alertConfig)
def RPCRequestAddSeekTimestamp(builder, seekTimestamp): builder.PrependInt64Slot(6, seekTimestamp, 0)
def AddSeekTimestamp(builder, seekTimestamp):
    return RPCRequestAddSeekTimestamp(builder, seekTimestamp)
def RPCRequestAddSpeedMultiplier(builder, speedMultiplier): builder.PrependFloat32Slot(7, speedMultiplier, 0.0)
def AddSpeedMultiplier(builder, speedMultiplier):
    return RPCRequestAddSpeedMultiplier(builder, speedMultiplier)
def RPCRequestEnd(builder): return builder.EndObject()
def End(builder):
    return RPCRequestEnd(builder)