# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SubscriptionPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SubscriptionPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubscriptionPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SubscriptionPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SubscriptionPayload
    def Symbols(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # SubscriptionPayload
    def SymbolsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SubscriptionPayload
    def SymbolsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SubscriptionPayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    SubscriptionPayloadStart(builder)

def SubscriptionPayloadAddSymbols(builder, symbols):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(symbols), 0)

def AddSymbols(builder, symbols):
    SubscriptionPayloadAddSymbols(builder, symbols)

def SubscriptionPayloadStartSymbolsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSymbolsVector(builder, numElems):
    return SubscriptionPayloadStartSymbolsVector(builder, numElems)

def SubscriptionPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return SubscriptionPayloadEnd(builder)
