# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Tick(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Tick()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTick(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Tick
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Tick
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Tick
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Tick
    def Price(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def Bid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def Ask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def BidSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Tick
    def AskSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def TickStart(builder):
    builder.StartObject(8)

def Start(builder):
    TickStart(builder)

def TickAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    TickAddTimestamp(builder, timestamp)

def TickAddSymbol(builder, symbol):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)

def AddSymbol(builder, symbol):
    TickAddSymbol(builder, symbol)

def TickAddPrice(builder, price):
    builder.PrependFloat64Slot(2, price, 0.0)

def AddPrice(builder, price):
    TickAddPrice(builder, price)

def TickAddVolume(builder, volume):
    builder.PrependFloat64Slot(3, volume, 0.0)

def AddVolume(builder, volume):
    TickAddVolume(builder, volume)

def TickAddBid(builder, bid):
    builder.PrependFloat64Slot(4, bid, 0.0)

def AddBid(builder, bid):
    TickAddBid(builder, bid)

def TickAddAsk(builder, ask):
    builder.PrependFloat64Slot(5, ask, 0.0)

def AddAsk(builder, ask):
    TickAddAsk(builder, ask)

def TickAddBidSize(builder, bidSize):
    builder.PrependFloat64Slot(6, bidSize, 0.0)

def AddBidSize(builder, bidSize):
    TickAddBidSize(builder, bidSize)

def TickAddAskSize(builder, askSize):
    builder.PrependFloat64Slot(7, askSize, 0.0)

def AddAskSize(builder, askSize):
    TickAddAskSize(builder, askSize)

def TickEnd(builder):
    return builder.EndObject()

def End(builder):
    return TickEnd(builder)
