// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod nexus_quant {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod protocol {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

// struct Point, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Point(pub [u8; 16]);
impl Default for Point {
  fn default() -> Self {
    Self([0; 16])
  }
}
impl core::fmt::Debug for Point {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Point")
      .field("x", &self.x())
      .field("y", &self.y())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Point {}
impl flatbuffers::SafeSliceAccess for Point {}
impl<'a> flatbuffers::Follow<'a> for Point {
  type Inner = &'a Point;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Point>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Point {
  type Inner = &'a Point;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Point>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Point {
    type Output = Point;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(self as *const Point as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Point {
    type Output = Point;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(*self as *const Point as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Point {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Point {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    x: f64,
    y: f64,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_x(x);
    s.set_y(y);
    s
  }

  pub fn x(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<f64>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<f64>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_x(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const f64 as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<f64>(),
      );
    }
  }

  pub fn y(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<f64>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<f64>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_y(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const f64 as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<f64>(),
      );
    }
  }

}

// struct Color, aligned to 1
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Color(pub [u8; 4]);
impl Default for Color {
  fn default() -> Self {
    Self([0; 4])
  }
}
impl core::fmt::Debug for Color {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Color")
      .field("r", &self.r())
      .field("g", &self.g())
      .field("b", &self.b())
      .field("a", &self.a())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Color {}
impl flatbuffers::SafeSliceAccess for Color {}
impl<'a> flatbuffers::Follow<'a> for Color {
  type Inner = &'a Color;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Color>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Color {
  type Inner = &'a Color;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Color>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Color {
    type Output = Color;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(self as *const Color as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Color {
    type Output = Color;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(*self as *const Color as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Color {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Color {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    r: u8,
    g: u8,
    b: u8,
    a: u8,
  ) -> Self {
    let mut s = Self([0; 4]);
    s.set_r(r);
    s.set_g(g);
    s.set_b(b);
    s.set_a(a);
    s
  }

  pub fn r(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<u8>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u8>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_r(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u8 as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<u8>(),
      );
    }
  }

  pub fn g(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<u8>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[1..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u8>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_g(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u8 as *const u8,
        self.0[1..].as_mut_ptr(),
        core::mem::size_of::<u8>(),
      );
    }
  }

  pub fn b(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<u8>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[2..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u8>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_b(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u8 as *const u8,
        self.0[2..].as_mut_ptr(),
        core::mem::size_of::<u8>(),
      );
    }
  }

  pub fn a(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<u8>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[3..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u8>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_a(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u8 as *const u8,
        self.0[3..].as_mut_ptr(),
        core::mem::size_of::<u8>(),
      );
    }
  }

}

pub enum DrawingLineOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DrawingLine<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DrawingLine<'a> {
  type Inner = DrawingLine<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> DrawingLine<'a> {
  pub const VT_START: flatbuffers::VOffsetT = 4;
  pub const VT_END: flatbuffers::VOffsetT = 6;
  pub const VT_COLOR: flatbuffers::VOffsetT = 8;
  pub const VT_WIDTH: flatbuffers::VOffsetT = 10;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DrawingLine { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args DrawingLineArgs<'args>
  ) -> flatbuffers::WIPOffset<DrawingLine<'bldr>> {
    let mut builder = DrawingLineBuilder::new(_fbb);
    builder.add_width(args.width);
    if let Some(x) = args.color { builder.add_color(x); }
    if let Some(x) = args.end { builder.add_end(x); }
    if let Some(x) = args.start { builder.add_start(x); }
    builder.finish()
  }


  #[inline]
  pub fn start(&self) -> Option<&'a Point> {
    self._tab.get::<Point>(DrawingLine::VT_START, None)
  }
  #[inline]
  pub fn end(&self) -> Option<&'a Point> {
    self._tab.get::<Point>(DrawingLine::VT_END, None)
  }
  #[inline]
  pub fn color(&self) -> Option<&'a Color> {
    self._tab.get::<Color>(DrawingLine::VT_COLOR, None)
  }
  #[inline]
  pub fn width(&self) -> f32 {
    self._tab.get::<f32>(DrawingLine::VT_WIDTH, Some(0.0)).unwrap()
  }
}

impl flatbuffers::Verifiable for DrawingLine<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<Point>("start", Self::VT_START, false)?
     .visit_field::<Point>("end", Self::VT_END, false)?
     .visit_field::<Color>("color", Self::VT_COLOR, false)?
     .visit_field::<f32>("width", Self::VT_WIDTH, false)?
     .finish();
    Ok(())
  }
}
pub struct DrawingLineArgs<'a> {
    pub start: Option<&'a Point>,
    pub end: Option<&'a Point>,
    pub color: Option<&'a Color>,
    pub width: f32,
}
impl<'a> Default for DrawingLineArgs<'a> {
  #[inline]
  fn default() -> Self {
    DrawingLineArgs {
      start: None,
      end: None,
      color: None,
      width: 0.0,
    }
  }
}

pub struct DrawingLineBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> DrawingLineBuilder<'a, 'b> {
  #[inline]
  pub fn add_start(&mut self, start: &Point) {
    self.fbb_.push_slot_always::<&Point>(DrawingLine::VT_START, start);
  }
  #[inline]
  pub fn add_end(&mut self, end: &Point) {
    self.fbb_.push_slot_always::<&Point>(DrawingLine::VT_END, end);
  }
  #[inline]
  pub fn add_color(&mut self, color: &Color) {
    self.fbb_.push_slot_always::<&Color>(DrawingLine::VT_COLOR, color);
  }
  #[inline]
  pub fn add_width(&mut self, width: f32) {
    self.fbb_.push_slot::<f32>(DrawingLine::VT_WIDTH, width, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> DrawingLineBuilder<'a, 'b> {
    let start = _fbb.start_table();
    DrawingLineBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DrawingLine<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DrawingLine<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DrawingLine");
      ds.field("start", &self.start());
      ds.field("end", &self.end());
      ds.field("color", &self.color());
      ds.field("width", &self.width());
      ds.finish()
  }
}
pub enum DrawingRectOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DrawingRect<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DrawingRect<'a> {
  type Inner = DrawingRect<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> DrawingRect<'a> {
  pub const VT_X1: flatbuffers::VOffsetT = 4;
  pub const VT_Y1: flatbuffers::VOffsetT = 6;
  pub const VT_X2: flatbuffers::VOffsetT = 8;
  pub const VT_Y2: flatbuffers::VOffsetT = 10;
  pub const VT_COLOR: flatbuffers::VOffsetT = 12;
  pub const VT_FILL: flatbuffers::VOffsetT = 14;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DrawingRect { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args DrawingRectArgs<'args>
  ) -> flatbuffers::WIPOffset<DrawingRect<'bldr>> {
    let mut builder = DrawingRectBuilder::new(_fbb);
    builder.add_y2(args.y2);
    builder.add_x2(args.x2);
    builder.add_y1(args.y1);
    builder.add_x1(args.x1);
    if let Some(x) = args.color { builder.add_color(x); }
    builder.add_fill(args.fill);
    builder.finish()
  }


  #[inline]
  pub fn x1(&self) -> f64 {
    self._tab.get::<f64>(DrawingRect::VT_X1, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn y1(&self) -> f64 {
    self._tab.get::<f64>(DrawingRect::VT_Y1, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn x2(&self) -> f64 {
    self._tab.get::<f64>(DrawingRect::VT_X2, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn y2(&self) -> f64 {
    self._tab.get::<f64>(DrawingRect::VT_Y2, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn color(&self) -> Option<&'a Color> {
    self._tab.get::<Color>(DrawingRect::VT_COLOR, None)
  }
  #[inline]
  pub fn fill(&self) -> bool {
    self._tab.get::<bool>(DrawingRect::VT_FILL, Some(false)).unwrap()
  }
}

impl flatbuffers::Verifiable for DrawingRect<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<f64>("x1", Self::VT_X1, false)?
     .visit_field::<f64>("y1", Self::VT_Y1, false)?
     .visit_field::<f64>("x2", Self::VT_X2, false)?
     .visit_field::<f64>("y2", Self::VT_Y2, false)?
     .visit_field::<Color>("color", Self::VT_COLOR, false)?
     .visit_field::<bool>("fill", Self::VT_FILL, false)?
     .finish();
    Ok(())
  }
}
pub struct DrawingRectArgs<'a> {
    pub x1: f64,
    pub y1: f64,
    pub x2: f64,
    pub y2: f64,
    pub color: Option<&'a Color>,
    pub fill: bool,
}
impl<'a> Default for DrawingRectArgs<'a> {
  #[inline]
  fn default() -> Self {
    DrawingRectArgs {
      x1: 0.0,
      y1: 0.0,
      x2: 0.0,
      y2: 0.0,
      color: None,
      fill: false,
    }
  }
}

pub struct DrawingRectBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> DrawingRectBuilder<'a, 'b> {
  #[inline]
  pub fn add_x1(&mut self, x1: f64) {
    self.fbb_.push_slot::<f64>(DrawingRect::VT_X1, x1, 0.0);
  }
  #[inline]
  pub fn add_y1(&mut self, y1: f64) {
    self.fbb_.push_slot::<f64>(DrawingRect::VT_Y1, y1, 0.0);
  }
  #[inline]
  pub fn add_x2(&mut self, x2: f64) {
    self.fbb_.push_slot::<f64>(DrawingRect::VT_X2, x2, 0.0);
  }
  #[inline]
  pub fn add_y2(&mut self, y2: f64) {
    self.fbb_.push_slot::<f64>(DrawingRect::VT_Y2, y2, 0.0);
  }
  #[inline]
  pub fn add_color(&mut self, color: &Color) {
    self.fbb_.push_slot_always::<&Color>(DrawingRect::VT_COLOR, color);
  }
  #[inline]
  pub fn add_fill(&mut self, fill: bool) {
    self.fbb_.push_slot::<bool>(DrawingRect::VT_FILL, fill, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> DrawingRectBuilder<'a, 'b> {
    let start = _fbb.start_table();
    DrawingRectBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DrawingRect<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DrawingRect<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DrawingRect");
      ds.field("x1", &self.x1());
      ds.field("y1", &self.y1());
      ds.field("x2", &self.x2());
      ds.field("y2", &self.y2());
      ds.field("color", &self.color());
      ds.field("fill", &self.fill());
      ds.finish()
  }
}
pub enum DrawingPolygonOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DrawingPolygon<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DrawingPolygon<'a> {
  type Inner = DrawingPolygon<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> DrawingPolygon<'a> {
  pub const VT_POINTS: flatbuffers::VOffsetT = 4;
  pub const VT_COLOR: flatbuffers::VOffsetT = 6;
  pub const VT_FILL: flatbuffers::VOffsetT = 8;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DrawingPolygon { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args DrawingPolygonArgs<'args>
  ) -> flatbuffers::WIPOffset<DrawingPolygon<'bldr>> {
    let mut builder = DrawingPolygonBuilder::new(_fbb);
    if let Some(x) = args.color { builder.add_color(x); }
    if let Some(x) = args.points { builder.add_points(x); }
    builder.add_fill(args.fill);
    builder.finish()
  }


  #[inline]
  pub fn points(&self) -> Option<&'a [Point]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Point>>>(DrawingPolygon::VT_POINTS, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn color(&self) -> Option<&'a Color> {
    self._tab.get::<Color>(DrawingPolygon::VT_COLOR, None)
  }
  #[inline]
  pub fn fill(&self) -> bool {
    self._tab.get::<bool>(DrawingPolygon::VT_FILL, Some(false)).unwrap()
  }
}

impl flatbuffers::Verifiable for DrawingPolygon<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Point>>>("points", Self::VT_POINTS, false)?
     .visit_field::<Color>("color", Self::VT_COLOR, false)?
     .visit_field::<bool>("fill", Self::VT_FILL, false)?
     .finish();
    Ok(())
  }
}
pub struct DrawingPolygonArgs<'a> {
    pub points: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Point>>>,
    pub color: Option<&'a Color>,
    pub fill: bool,
}
impl<'a> Default for DrawingPolygonArgs<'a> {
  #[inline]
  fn default() -> Self {
    DrawingPolygonArgs {
      points: None,
      color: None,
      fill: false,
    }
  }
}

pub struct DrawingPolygonBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> DrawingPolygonBuilder<'a, 'b> {
  #[inline]
  pub fn add_points(&mut self, points: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Point>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DrawingPolygon::VT_POINTS, points);
  }
  #[inline]
  pub fn add_color(&mut self, color: &Color) {
    self.fbb_.push_slot_always::<&Color>(DrawingPolygon::VT_COLOR, color);
  }
  #[inline]
  pub fn add_fill(&mut self, fill: bool) {
    self.fbb_.push_slot::<bool>(DrawingPolygon::VT_FILL, fill, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> DrawingPolygonBuilder<'a, 'b> {
    let start = _fbb.start_table();
    DrawingPolygonBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DrawingPolygon<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DrawingPolygon<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DrawingPolygon");
      ds.field("points", &self.points());
      ds.field("color", &self.color());
      ds.field("fill", &self.fill());
      ds.finish()
  }
}
pub enum DrawingTextOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DrawingText<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DrawingText<'a> {
  type Inner = DrawingText<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> DrawingText<'a> {
  pub const VT_X: flatbuffers::VOffsetT = 4;
  pub const VT_Y: flatbuffers::VOffsetT = 6;
  pub const VT_TEXT: flatbuffers::VOffsetT = 8;
  pub const VT_COLOR: flatbuffers::VOffsetT = 10;
  pub const VT_SIZE_: flatbuffers::VOffsetT = 12;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DrawingText { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args DrawingTextArgs<'args>
  ) -> flatbuffers::WIPOffset<DrawingText<'bldr>> {
    let mut builder = DrawingTextBuilder::new(_fbb);
    builder.add_y(args.y);
    builder.add_x(args.x);
    builder.add_size_(args.size_);
    if let Some(x) = args.color { builder.add_color(x); }
    if let Some(x) = args.text { builder.add_text(x); }
    builder.finish()
  }


  #[inline]
  pub fn x(&self) -> f64 {
    self._tab.get::<f64>(DrawingText::VT_X, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn y(&self) -> f64 {
    self._tab.get::<f64>(DrawingText::VT_Y, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn text(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DrawingText::VT_TEXT, None)
  }
  #[inline]
  pub fn color(&self) -> Option<&'a Color> {
    self._tab.get::<Color>(DrawingText::VT_COLOR, None)
  }
  #[inline]
  pub fn size_(&self) -> f32 {
    self._tab.get::<f32>(DrawingText::VT_SIZE_, Some(0.0)).unwrap()
  }
}

impl flatbuffers::Verifiable for DrawingText<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<f64>("x", Self::VT_X, false)?
     .visit_field::<f64>("y", Self::VT_Y, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("text", Self::VT_TEXT, false)?
     .visit_field::<Color>("color", Self::VT_COLOR, false)?
     .visit_field::<f32>("size_", Self::VT_SIZE_, false)?
     .finish();
    Ok(())
  }
}
pub struct DrawingTextArgs<'a> {
    pub x: f64,
    pub y: f64,
    pub text: Option<flatbuffers::WIPOffset<&'a str>>,
    pub color: Option<&'a Color>,
    pub size_: f32,
}
impl<'a> Default for DrawingTextArgs<'a> {
  #[inline]
  fn default() -> Self {
    DrawingTextArgs {
      x: 0.0,
      y: 0.0,
      text: None,
      color: None,
      size_: 0.0,
    }
  }
}

pub struct DrawingTextBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> DrawingTextBuilder<'a, 'b> {
  #[inline]
  pub fn add_x(&mut self, x: f64) {
    self.fbb_.push_slot::<f64>(DrawingText::VT_X, x, 0.0);
  }
  #[inline]
  pub fn add_y(&mut self, y: f64) {
    self.fbb_.push_slot::<f64>(DrawingText::VT_Y, y, 0.0);
  }
  #[inline]
  pub fn add_text(&mut self, text: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DrawingText::VT_TEXT, text);
  }
  #[inline]
  pub fn add_color(&mut self, color: &Color) {
    self.fbb_.push_slot_always::<&Color>(DrawingText::VT_COLOR, color);
  }
  #[inline]
  pub fn add_size_(&mut self, size_: f32) {
    self.fbb_.push_slot::<f32>(DrawingText::VT_SIZE_, size_, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> DrawingTextBuilder<'a, 'b> {
    let start = _fbb.start_table();
    DrawingTextBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DrawingText<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DrawingText<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DrawingText");
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("text", &self.text());
      ds.field("color", &self.color());
      ds.field("size_", &self.size_());
      ds.finish()
  }
}
pub enum IndicatorValueOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IndicatorValue<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for IndicatorValue<'a> {
  type Inner = IndicatorValue<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> IndicatorValue<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_TIMESTAMPS: flatbuffers::VOffsetT = 6;
  pub const VT_VALUES: flatbuffers::VOffsetT = 8;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    IndicatorValue { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args IndicatorValueArgs<'args>
  ) -> flatbuffers::WIPOffset<IndicatorValue<'bldr>> {
    let mut builder = IndicatorValueBuilder::new(_fbb);
    if let Some(x) = args.values { builder.add_values(x); }
    if let Some(x) = args.timestamps { builder.add_timestamps(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(IndicatorValue::VT_NAME, None)
  }
  #[inline]
  pub fn timestamps(&self) -> Option<flatbuffers::Vector<'a, i64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i64>>>(IndicatorValue::VT_TIMESTAMPS, None)
  }
  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(IndicatorValue::VT_VALUES, None)
  }
}

impl flatbuffers::Verifiable for IndicatorValue<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i64>>>("timestamps", Self::VT_TIMESTAMPS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f64>>>("values", Self::VT_VALUES, false)?
     .finish();
    Ok(())
  }
}
pub struct IndicatorValueArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub timestamps: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i64>>>,
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
}
impl<'a> Default for IndicatorValueArgs<'a> {
  #[inline]
  fn default() -> Self {
    IndicatorValueArgs {
      name: None,
      timestamps: None,
      values: None,
    }
  }
}

pub struct IndicatorValueBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> IndicatorValueBuilder<'a, 'b> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IndicatorValue::VT_NAME, name);
  }
  #[inline]
  pub fn add_timestamps(&mut self, timestamps: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IndicatorValue::VT_TIMESTAMPS, timestamps);
  }
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IndicatorValue::VT_VALUES, values);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> IndicatorValueBuilder<'a, 'b> {
    let start = _fbb.start_table();
    IndicatorValueBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<IndicatorValue<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for IndicatorValue<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("IndicatorValue");
      ds.field("name", &self.name());
      ds.field("timestamps", &self.timestamps());
      ds.field("values", &self.values());
      ds.finish()
  }
}
pub enum IndicatorPayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IndicatorPayload<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for IndicatorPayload<'a> {
  type Inner = IndicatorPayload<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> IndicatorPayload<'a> {
  pub const VT_INDICATOR_ID: flatbuffers::VOffsetT = 4;
  pub const VT_VALUES: flatbuffers::VOffsetT = 6;
  pub const VT_LINES: flatbuffers::VOffsetT = 8;
  pub const VT_RECTANGLES: flatbuffers::VOffsetT = 10;
  pub const VT_POLYGONS: flatbuffers::VOffsetT = 12;
  pub const VT_TEXTS: flatbuffers::VOffsetT = 14;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    IndicatorPayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args IndicatorPayloadArgs<'args>
  ) -> flatbuffers::WIPOffset<IndicatorPayload<'bldr>> {
    let mut builder = IndicatorPayloadBuilder::new(_fbb);
    if let Some(x) = args.texts { builder.add_texts(x); }
    if let Some(x) = args.polygons { builder.add_polygons(x); }
    if let Some(x) = args.rectangles { builder.add_rectangles(x); }
    if let Some(x) = args.lines { builder.add_lines(x); }
    if let Some(x) = args.values { builder.add_values(x); }
    if let Some(x) = args.indicator_id { builder.add_indicator_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn indicator_id(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(IndicatorPayload::VT_INDICATOR_ID, None)
  }
  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<IndicatorValue<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<IndicatorValue>>>>(IndicatorPayload::VT_VALUES, None)
  }
  #[inline]
  pub fn lines(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingLine<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingLine>>>>(IndicatorPayload::VT_LINES, None)
  }
  #[inline]
  pub fn rectangles(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingRect<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingRect>>>>(IndicatorPayload::VT_RECTANGLES, None)
  }
  #[inline]
  pub fn polygons(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingPolygon<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingPolygon>>>>(IndicatorPayload::VT_POLYGONS, None)
  }
  #[inline]
  pub fn texts(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingText<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingText>>>>(IndicatorPayload::VT_TEXTS, None)
  }
}

impl flatbuffers::Verifiable for IndicatorPayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("indicator_id", Self::VT_INDICATOR_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<IndicatorValue>>>>("values", Self::VT_VALUES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<DrawingLine>>>>("lines", Self::VT_LINES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<DrawingRect>>>>("rectangles", Self::VT_RECTANGLES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<DrawingPolygon>>>>("polygons", Self::VT_POLYGONS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<DrawingText>>>>("texts", Self::VT_TEXTS, false)?
     .finish();
    Ok(())
  }
}
pub struct IndicatorPayloadArgs<'a> {
    pub indicator_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<IndicatorValue<'a>>>>>,
    pub lines: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingLine<'a>>>>>,
    pub rectangles: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingRect<'a>>>>>,
    pub polygons: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingPolygon<'a>>>>>,
    pub texts: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DrawingText<'a>>>>>,
}
impl<'a> Default for IndicatorPayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    IndicatorPayloadArgs {
      indicator_id: None,
      values: None,
      lines: None,
      rectangles: None,
      polygons: None,
      texts: None,
    }
  }
}

pub struct IndicatorPayloadBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> IndicatorPayloadBuilder<'a, 'b> {
  #[inline]
  pub fn add_indicator_id(&mut self, indicator_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IndicatorPayload::VT_INDICATOR_ID, indicator_id);
  }
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<IndicatorValue<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IndicatorPayload::VT_VALUES, values);
  }
  #[inline]
  pub fn add_lines(&mut self, lines: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<DrawingLine<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IndicatorPayload::VT_LINES, lines);
  }
  #[inline]
  pub fn add_rectangles(&mut self, rectangles: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<DrawingRect<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IndicatorPayload::VT_RECTANGLES, rectangles);
  }
  #[inline]
  pub fn add_polygons(&mut self, polygons: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<DrawingPolygon<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IndicatorPayload::VT_POLYGONS, polygons);
  }
  #[inline]
  pub fn add_texts(&mut self, texts: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<DrawingText<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IndicatorPayload::VT_TEXTS, texts);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> IndicatorPayloadBuilder<'a, 'b> {
    let start = _fbb.start_table();
    IndicatorPayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<IndicatorPayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for IndicatorPayload<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("IndicatorPayload");
      ds.field("indicator_id", &self.indicator_id());
      ds.field("values", &self.values());
      ds.field("lines", &self.lines());
      ds.field("rectangles", &self.rectangles());
      ds.field("polygons", &self.polygons());
      ds.field("texts", &self.texts());
      ds.finish()
  }
}
#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_root_as_indicator_payload<'a>(buf: &'a [u8]) -> IndicatorPayload<'a> {
  unsafe { flatbuffers::root_unchecked::<IndicatorPayload<'a>>(buf) }
}

#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_size_prefixed_root_as_indicator_payload<'a>(buf: &'a [u8]) -> IndicatorPayload<'a> {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<IndicatorPayload<'a>>(buf) }
}

#[inline]
/// Verifies that a buffer of bytes contains a `IndicatorPayload`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_indicator_payload_unchecked`.
pub fn root_as_indicator_payload(buf: &[u8]) -> Result<IndicatorPayload, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<IndicatorPayload>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `IndicatorPayload` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_indicator_payload_unchecked`.
pub fn size_prefixed_root_as_indicator_payload(buf: &[u8]) -> Result<IndicatorPayload, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<IndicatorPayload>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `IndicatorPayload` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_indicator_payload_unchecked`.
pub fn root_as_indicator_payload_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<IndicatorPayload<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<IndicatorPayload<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `IndicatorPayload` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_indicator_payload_unchecked`.
pub fn size_prefixed_root_as_indicator_payload_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<IndicatorPayload<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<IndicatorPayload<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a IndicatorPayload and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `IndicatorPayload`.
pub unsafe fn root_as_indicator_payload_unchecked(buf: &[u8]) -> IndicatorPayload {
  flatbuffers::root_unchecked::<IndicatorPayload>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed IndicatorPayload and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `IndicatorPayload`.
pub unsafe fn size_prefixed_root_as_indicator_payload_unchecked(buf: &[u8]) -> IndicatorPayload {
  flatbuffers::size_prefixed_root_unchecked::<IndicatorPayload>(buf)
}
#[inline]
pub fn finish_indicator_payload_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<IndicatorPayload<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_indicator_payload_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<IndicatorPayload<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Protocol
}  // pub mod NexusQuant
