// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod nexus_quant {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod protocol {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum TickOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Tick<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Tick<'a> {
  type Inner = Tick<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> Tick<'a> {
  pub const VT_TIMESTAMP: flatbuffers::VOffsetT = 4;
  pub const VT_SYMBOL: flatbuffers::VOffsetT = 6;
  pub const VT_PRICE: flatbuffers::VOffsetT = 8;
  pub const VT_VOLUME: flatbuffers::VOffsetT = 10;
  pub const VT_BID: flatbuffers::VOffsetT = 12;
  pub const VT_ASK: flatbuffers::VOffsetT = 14;
  pub const VT_BID_SIZE: flatbuffers::VOffsetT = 16;
  pub const VT_ASK_SIZE: flatbuffers::VOffsetT = 18;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Tick { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TickArgs<'args>
  ) -> flatbuffers::WIPOffset<Tick<'bldr>> {
    let mut builder = TickBuilder::new(_fbb);
    builder.add_ask_size(args.ask_size);
    builder.add_bid_size(args.bid_size);
    builder.add_ask(args.ask);
    builder.add_bid(args.bid);
    builder.add_volume(args.volume);
    builder.add_price(args.price);
    builder.add_timestamp(args.timestamp);
    if let Some(x) = args.symbol { builder.add_symbol(x); }
    builder.finish()
  }


  #[inline]
  pub fn timestamp(&self) -> i64 {
    self._tab.get::<i64>(Tick::VT_TIMESTAMP, Some(0)).unwrap()
  }
  #[inline]
  pub fn symbol(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Tick::VT_SYMBOL, None)
  }
  #[inline]
  pub fn price(&self) -> f64 {
    self._tab.get::<f64>(Tick::VT_PRICE, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn volume(&self) -> f64 {
    self._tab.get::<f64>(Tick::VT_VOLUME, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn bid(&self) -> f64 {
    self._tab.get::<f64>(Tick::VT_BID, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn ask(&self) -> f64 {
    self._tab.get::<f64>(Tick::VT_ASK, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn bid_size(&self) -> f64 {
    self._tab.get::<f64>(Tick::VT_BID_SIZE, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn ask_size(&self) -> f64 {
    self._tab.get::<f64>(Tick::VT_ASK_SIZE, Some(0.0)).unwrap()
  }
}

impl flatbuffers::Verifiable for Tick<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("symbol", Self::VT_SYMBOL, false)?
     .visit_field::<f64>("price", Self::VT_PRICE, false)?
     .visit_field::<f64>("volume", Self::VT_VOLUME, false)?
     .visit_field::<f64>("bid", Self::VT_BID, false)?
     .visit_field::<f64>("ask", Self::VT_ASK, false)?
     .visit_field::<f64>("bid_size", Self::VT_BID_SIZE, false)?
     .visit_field::<f64>("ask_size", Self::VT_ASK_SIZE, false)?
     .finish();
    Ok(())
  }
}
pub struct TickArgs<'a> {
    pub timestamp: i64,
    pub symbol: Option<flatbuffers::WIPOffset<&'a str>>,
    pub price: f64,
    pub volume: f64,
    pub bid: f64,
    pub ask: f64,
    pub bid_size: f64,
    pub ask_size: f64,
}
impl<'a> Default for TickArgs<'a> {
  #[inline]
  fn default() -> Self {
    TickArgs {
      timestamp: 0,
      symbol: None,
      price: 0.0,
      volume: 0.0,
      bid: 0.0,
      ask: 0.0,
      bid_size: 0.0,
      ask_size: 0.0,
    }
  }
}

pub struct TickBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TickBuilder<'a, 'b> {
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: i64) {
    self.fbb_.push_slot::<i64>(Tick::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn add_symbol(&mut self, symbol: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Tick::VT_SYMBOL, symbol);
  }
  #[inline]
  pub fn add_price(&mut self, price: f64) {
    self.fbb_.push_slot::<f64>(Tick::VT_PRICE, price, 0.0);
  }
  #[inline]
  pub fn add_volume(&mut self, volume: f64) {
    self.fbb_.push_slot::<f64>(Tick::VT_VOLUME, volume, 0.0);
  }
  #[inline]
  pub fn add_bid(&mut self, bid: f64) {
    self.fbb_.push_slot::<f64>(Tick::VT_BID, bid, 0.0);
  }
  #[inline]
  pub fn add_ask(&mut self, ask: f64) {
    self.fbb_.push_slot::<f64>(Tick::VT_ASK, ask, 0.0);
  }
  #[inline]
  pub fn add_bid_size(&mut self, bid_size: f64) {
    self.fbb_.push_slot::<f64>(Tick::VT_BID_SIZE, bid_size, 0.0);
  }
  #[inline]
  pub fn add_ask_size(&mut self, ask_size: f64) {
    self.fbb_.push_slot::<f64>(Tick::VT_ASK_SIZE, ask_size, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TickBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TickBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Tick<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Tick<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Tick");
      ds.field("timestamp", &self.timestamp());
      ds.field("symbol", &self.symbol());
      ds.field("price", &self.price());
      ds.field("volume", &self.volume());
      ds.field("bid", &self.bid());
      ds.field("ask", &self.ask());
      ds.field("bid_size", &self.bid_size());
      ds.field("ask_size", &self.ask_size());
      ds.finish()
  }
}
pub enum CandleOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Candle<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Candle<'a> {
  type Inner = Candle<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> Candle<'a> {
  pub const VT_TIMESTAMP: flatbuffers::VOffsetT = 4;
  pub const VT_SYMBOL: flatbuffers::VOffsetT = 6;
  pub const VT_OPEN: flatbuffers::VOffsetT = 8;
  pub const VT_HIGH: flatbuffers::VOffsetT = 10;
  pub const VT_LOW: flatbuffers::VOffsetT = 12;
  pub const VT_CLOSE: flatbuffers::VOffsetT = 14;
  pub const VT_VOLUME: flatbuffers::VOffsetT = 16;
  pub const VT_VWAP: flatbuffers::VOffsetT = 18;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Candle { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args CandleArgs<'args>
  ) -> flatbuffers::WIPOffset<Candle<'bldr>> {
    let mut builder = CandleBuilder::new(_fbb);
    builder.add_vwap(args.vwap);
    builder.add_volume(args.volume);
    builder.add_close(args.close);
    builder.add_low(args.low);
    builder.add_high(args.high);
    builder.add_open(args.open);
    builder.add_timestamp(args.timestamp);
    if let Some(x) = args.symbol { builder.add_symbol(x); }
    builder.finish()
  }


  #[inline]
  pub fn timestamp(&self) -> i64 {
    self._tab.get::<i64>(Candle::VT_TIMESTAMP, Some(0)).unwrap()
  }
  #[inline]
  pub fn symbol(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Candle::VT_SYMBOL, None)
  }
  #[inline]
  pub fn open(&self) -> f64 {
    self._tab.get::<f64>(Candle::VT_OPEN, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn high(&self) -> f64 {
    self._tab.get::<f64>(Candle::VT_HIGH, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn low(&self) -> f64 {
    self._tab.get::<f64>(Candle::VT_LOW, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn close(&self) -> f64 {
    self._tab.get::<f64>(Candle::VT_CLOSE, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn volume(&self) -> f64 {
    self._tab.get::<f64>(Candle::VT_VOLUME, Some(0.0)).unwrap()
  }
  #[inline]
  pub fn vwap(&self) -> f64 {
    self._tab.get::<f64>(Candle::VT_VWAP, Some(0.0)).unwrap()
  }
}

impl flatbuffers::Verifiable for Candle<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("symbol", Self::VT_SYMBOL, false)?
     .visit_field::<f64>("open", Self::VT_OPEN, false)?
     .visit_field::<f64>("high", Self::VT_HIGH, false)?
     .visit_field::<f64>("low", Self::VT_LOW, false)?
     .visit_field::<f64>("close", Self::VT_CLOSE, false)?
     .visit_field::<f64>("volume", Self::VT_VOLUME, false)?
     .visit_field::<f64>("vwap", Self::VT_VWAP, false)?
     .finish();
    Ok(())
  }
}
pub struct CandleArgs<'a> {
    pub timestamp: i64,
    pub symbol: Option<flatbuffers::WIPOffset<&'a str>>,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
    pub vwap: f64,
}
impl<'a> Default for CandleArgs<'a> {
  #[inline]
  fn default() -> Self {
    CandleArgs {
      timestamp: 0,
      symbol: None,
      open: 0.0,
      high: 0.0,
      low: 0.0,
      close: 0.0,
      volume: 0.0,
      vwap: 0.0,
    }
  }
}

pub struct CandleBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> CandleBuilder<'a, 'b> {
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: i64) {
    self.fbb_.push_slot::<i64>(Candle::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn add_symbol(&mut self, symbol: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Candle::VT_SYMBOL, symbol);
  }
  #[inline]
  pub fn add_open(&mut self, open: f64) {
    self.fbb_.push_slot::<f64>(Candle::VT_OPEN, open, 0.0);
  }
  #[inline]
  pub fn add_high(&mut self, high: f64) {
    self.fbb_.push_slot::<f64>(Candle::VT_HIGH, high, 0.0);
  }
  #[inline]
  pub fn add_low(&mut self, low: f64) {
    self.fbb_.push_slot::<f64>(Candle::VT_LOW, low, 0.0);
  }
  #[inline]
  pub fn add_close(&mut self, close: f64) {
    self.fbb_.push_slot::<f64>(Candle::VT_CLOSE, close, 0.0);
  }
  #[inline]
  pub fn add_volume(&mut self, volume: f64) {
    self.fbb_.push_slot::<f64>(Candle::VT_VOLUME, volume, 0.0);
  }
  #[inline]
  pub fn add_vwap(&mut self, vwap: f64) {
    self.fbb_.push_slot::<f64>(Candle::VT_VWAP, vwap, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> CandleBuilder<'a, 'b> {
    let start = _fbb.start_table();
    CandleBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Candle<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Candle<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Candle");
      ds.field("timestamp", &self.timestamp());
      ds.field("symbol", &self.symbol());
      ds.field("open", &self.open());
      ds.field("high", &self.high());
      ds.field("low", &self.low());
      ds.field("close", &self.close());
      ds.field("volume", &self.volume());
      ds.field("vwap", &self.vwap());
      ds.finish()
  }
}
pub enum MarketDataBatchOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MarketDataBatch<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for MarketDataBatch<'a> {
  type Inner = MarketDataBatch<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> MarketDataBatch<'a> {
  pub const VT_TICKS: flatbuffers::VOffsetT = 4;
  pub const VT_CANDLES: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    MarketDataBatch { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args MarketDataBatchArgs<'args>
  ) -> flatbuffers::WIPOffset<MarketDataBatch<'bldr>> {
    let mut builder = MarketDataBatchBuilder::new(_fbb);
    if let Some(x) = args.candles { builder.add_candles(x); }
    if let Some(x) = args.ticks { builder.add_ticks(x); }
    builder.finish()
  }


  #[inline]
  pub fn ticks(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Tick<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Tick>>>>(MarketDataBatch::VT_TICKS, None)
  }
  #[inline]
  pub fn candles(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Candle<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Candle>>>>(MarketDataBatch::VT_CANDLES, None)
  }
}

impl flatbuffers::Verifiable for MarketDataBatch<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Tick>>>>("ticks", Self::VT_TICKS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Candle>>>>("candles", Self::VT_CANDLES, false)?
     .finish();
    Ok(())
  }
}
pub struct MarketDataBatchArgs<'a> {
    pub ticks: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Tick<'a>>>>>,
    pub candles: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Candle<'a>>>>>,
}
impl<'a> Default for MarketDataBatchArgs<'a> {
  #[inline]
  fn default() -> Self {
    MarketDataBatchArgs {
      ticks: None,
      candles: None,
    }
  }
}

pub struct MarketDataBatchBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> MarketDataBatchBuilder<'a, 'b> {
  #[inline]
  pub fn add_ticks(&mut self, ticks: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Tick<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MarketDataBatch::VT_TICKS, ticks);
  }
  #[inline]
  pub fn add_candles(&mut self, candles: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Candle<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MarketDataBatch::VT_CANDLES, candles);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MarketDataBatchBuilder<'a, 'b> {
    let start = _fbb.start_table();
    MarketDataBatchBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<MarketDataBatch<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for MarketDataBatch<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("MarketDataBatch");
      ds.field("ticks", &self.ticks());
      ds.field("candles", &self.candles());
      ds.finish()
  }
}
#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_root_as_market_data_batch<'a>(buf: &'a [u8]) -> MarketDataBatch<'a> {
  unsafe { flatbuffers::root_unchecked::<MarketDataBatch<'a>>(buf) }
}

#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_size_prefixed_root_as_market_data_batch<'a>(buf: &'a [u8]) -> MarketDataBatch<'a> {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<MarketDataBatch<'a>>(buf) }
}

#[inline]
/// Verifies that a buffer of bytes contains a `MarketDataBatch`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_market_data_batch_unchecked`.
pub fn root_as_market_data_batch(buf: &[u8]) -> Result<MarketDataBatch, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<MarketDataBatch>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `MarketDataBatch` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_market_data_batch_unchecked`.
pub fn size_prefixed_root_as_market_data_batch(buf: &[u8]) -> Result<MarketDataBatch, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<MarketDataBatch>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `MarketDataBatch` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_market_data_batch_unchecked`.
pub fn root_as_market_data_batch_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MarketDataBatch<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<MarketDataBatch<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `MarketDataBatch` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_market_data_batch_unchecked`.
pub fn size_prefixed_root_as_market_data_batch_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MarketDataBatch<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<MarketDataBatch<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a MarketDataBatch and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `MarketDataBatch`.
pub unsafe fn root_as_market_data_batch_unchecked(buf: &[u8]) -> MarketDataBatch {
  flatbuffers::root_unchecked::<MarketDataBatch>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed MarketDataBatch and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `MarketDataBatch`.
pub unsafe fn size_prefixed_root_as_market_data_batch_unchecked(buf: &[u8]) -> MarketDataBatch {
  flatbuffers::size_prefixed_root_unchecked::<MarketDataBatch>(buf)
}
#[inline]
pub fn finish_market_data_batch_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<MarketDataBatch<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_market_data_batch_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<MarketDataBatch<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Protocol
}  // pub mod NexusQuant
