// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod nexus_quant {

#[allow(unused_imports, dead_code)]
pub mod protocol {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_COMMAND_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_COMMAND_TYPE: i8 = 8;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_COMMAND_TYPE: [CommandType; 9] = [
  CommandType::Subscribe,
  CommandType::Unsubscribe,
  CommandType::ReplayStart,
  CommandType::ReplayPause,
  CommandType::ReplayStop,
  CommandType::ReplaySeek,
  CommandType::ReplaySpeed,
  CommandType::RegisterAlert,
  CommandType::TriggerAlert,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct CommandType(pub i8);
#[allow(non_upper_case_globals)]
impl CommandType {
  pub const Subscribe: Self = Self(0);
  pub const Unsubscribe: Self = Self(1);
  pub const ReplayStart: Self = Self(2);
  pub const ReplayPause: Self = Self(3);
  pub const ReplayStop: Self = Self(4);
  pub const ReplaySeek: Self = Self(5);
  pub const ReplaySpeed: Self = Self(6);
  pub const RegisterAlert: Self = Self(7);
  pub const TriggerAlert: Self = Self(8);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 8;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Subscribe,
    Self::Unsubscribe,
    Self::ReplayStart,
    Self::ReplayPause,
    Self::ReplayStop,
    Self::ReplaySeek,
    Self::ReplaySpeed,
    Self::RegisterAlert,
    Self::TriggerAlert,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Subscribe => Some("Subscribe"),
      Self::Unsubscribe => Some("Unsubscribe"),
      Self::ReplayStart => Some("ReplayStart"),
      Self::ReplayPause => Some("ReplayPause"),
      Self::ReplayStop => Some("ReplayStop"),
      Self::ReplaySeek => Some("ReplaySeek"),
      Self::ReplaySpeed => Some("ReplaySpeed"),
      Self::RegisterAlert => Some("RegisterAlert"),
      Self::TriggerAlert => Some("TriggerAlert"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for CommandType {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for CommandType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for CommandType {
    type Output = CommandType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for CommandType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for CommandType {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for CommandType {}
pub enum ReplayConfigOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReplayConfig<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReplayConfig<'a> {
  type Inner = ReplayConfig<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReplayConfig<'a> {
  pub const VT_SYMBOL: ::flatbuffers::VOffsetT = 4;
  pub const VT_START_TIME: ::flatbuffers::VOffsetT = 6;
  pub const VT_END_TIME: ::flatbuffers::VOffsetT = 8;
  pub const VT_SPEED: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReplayConfig { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReplayConfigArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReplayConfig<'bldr>> {
    let mut builder = ReplayConfigBuilder::new(_fbb);
    builder.add_end_time(args.end_time);
    builder.add_start_time(args.start_time);
    builder.add_speed(args.speed);
    if let Some(x) = args.symbol { builder.add_symbol(x); }
    builder.finish()
  }


  #[inline]
  pub fn symbol(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ReplayConfig::VT_SYMBOL, None)}
  }
  #[inline]
  pub fn start_time(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(ReplayConfig::VT_START_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn end_time(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(ReplayConfig::VT_END_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn speed(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(ReplayConfig::VT_SPEED, Some(0.0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ReplayConfig<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("symbol", Self::VT_SYMBOL, false)?
     .visit_field::<i64>("start_time", Self::VT_START_TIME, false)?
     .visit_field::<i64>("end_time", Self::VT_END_TIME, false)?
     .visit_field::<f32>("speed", Self::VT_SPEED, false)?
     .finish();
    Ok(())
  }
}
pub struct ReplayConfigArgs<'a> {
    pub symbol: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub start_time: i64,
    pub end_time: i64,
    pub speed: f32,
}
impl<'a> Default for ReplayConfigArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReplayConfigArgs {
      symbol: None,
      start_time: 0,
      end_time: 0,
      speed: 0.0,
    }
  }
}

pub struct ReplayConfigBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReplayConfigBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_symbol(&mut self, symbol: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReplayConfig::VT_SYMBOL, symbol);
  }
  #[inline]
  pub fn add_start_time(&mut self, start_time: i64) {
    self.fbb_.push_slot::<i64>(ReplayConfig::VT_START_TIME, start_time, 0);
  }
  #[inline]
  pub fn add_end_time(&mut self, end_time: i64) {
    self.fbb_.push_slot::<i64>(ReplayConfig::VT_END_TIME, end_time, 0);
  }
  #[inline]
  pub fn add_speed(&mut self, speed: f32) {
    self.fbb_.push_slot::<f32>(ReplayConfig::VT_SPEED, speed, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReplayConfigBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReplayConfigBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReplayConfig<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReplayConfig<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReplayConfig");
      ds.field("symbol", &self.symbol());
      ds.field("start_time", &self.start_time());
      ds.field("end_time", &self.end_time());
      ds.field("speed", &self.speed());
      ds.finish()
  }
}
pub enum SubscriptionPayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SubscriptionPayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SubscriptionPayload<'a> {
  type Inner = SubscriptionPayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SubscriptionPayload<'a> {
  pub const VT_SYMBOLS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SubscriptionPayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SubscriptionPayloadArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SubscriptionPayload<'bldr>> {
    let mut builder = SubscriptionPayloadBuilder::new(_fbb);
    if let Some(x) = args.symbols { builder.add_symbols(x); }
    builder.finish()
  }


  #[inline]
  pub fn symbols(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(SubscriptionPayload::VT_SYMBOLS, None)}
  }
}

impl ::flatbuffers::Verifiable for SubscriptionPayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("symbols", Self::VT_SYMBOLS, false)?
     .finish();
    Ok(())
  }
}
pub struct SubscriptionPayloadArgs<'a> {
    pub symbols: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
}
impl<'a> Default for SubscriptionPayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    SubscriptionPayloadArgs {
      symbols: None,
    }
  }
}

pub struct SubscriptionPayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SubscriptionPayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_symbols(&mut self, symbols: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SubscriptionPayload::VT_SYMBOLS, symbols);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SubscriptionPayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SubscriptionPayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SubscriptionPayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SubscriptionPayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SubscriptionPayload");
      ds.field("symbols", &self.symbols());
      ds.finish()
  }
}
pub enum AlertConfigOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AlertConfig<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for AlertConfig<'a> {
  type Inner = AlertConfig<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> AlertConfig<'a> {
  pub const VT_ALERT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_SYMBOL: ::flatbuffers::VOffsetT = 6;
  pub const VT_CONDITION_TYPE: ::flatbuffers::VOffsetT = 8;
  pub const VT_THRESHOLD: ::flatbuffers::VOffsetT = 10;
  pub const VT_ACTIVE: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    AlertConfig { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AlertConfigArgs<'args>
  ) -> ::flatbuffers::WIPOffset<AlertConfig<'bldr>> {
    let mut builder = AlertConfigBuilder::new(_fbb);
    builder.add_threshold(args.threshold);
    if let Some(x) = args.condition_type { builder.add_condition_type(x); }
    if let Some(x) = args.symbol { builder.add_symbol(x); }
    if let Some(x) = args.alert_id { builder.add_alert_id(x); }
    builder.add_active(args.active);
    builder.finish()
  }


  #[inline]
  pub fn alert_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(AlertConfig::VT_ALERT_ID, None)}
  }
  #[inline]
  pub fn symbol(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(AlertConfig::VT_SYMBOL, None)}
  }
  #[inline]
  pub fn condition_type(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(AlertConfig::VT_CONDITION_TYPE, None)}
  }
  #[inline]
  pub fn threshold(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(AlertConfig::VT_THRESHOLD, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn active(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(AlertConfig::VT_ACTIVE, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for AlertConfig<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("alert_id", Self::VT_ALERT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("symbol", Self::VT_SYMBOL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("condition_type", Self::VT_CONDITION_TYPE, false)?
     .visit_field::<f64>("threshold", Self::VT_THRESHOLD, false)?
     .visit_field::<bool>("active", Self::VT_ACTIVE, false)?
     .finish();
    Ok(())
  }
}
pub struct AlertConfigArgs<'a> {
    pub alert_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub symbol: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub condition_type: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub threshold: f64,
    pub active: bool,
}
impl<'a> Default for AlertConfigArgs<'a> {
  #[inline]
  fn default() -> Self {
    AlertConfigArgs {
      alert_id: None,
      symbol: None,
      condition_type: None,
      threshold: 0.0,
      active: false,
    }
  }
}

pub struct AlertConfigBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AlertConfigBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_alert_id(&mut self, alert_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AlertConfig::VT_ALERT_ID, alert_id);
  }
  #[inline]
  pub fn add_symbol(&mut self, symbol: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AlertConfig::VT_SYMBOL, symbol);
  }
  #[inline]
  pub fn add_condition_type(&mut self, condition_type: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AlertConfig::VT_CONDITION_TYPE, condition_type);
  }
  #[inline]
  pub fn add_threshold(&mut self, threshold: f64) {
    self.fbb_.push_slot::<f64>(AlertConfig::VT_THRESHOLD, threshold, 0.0);
  }
  #[inline]
  pub fn add_active(&mut self, active: bool) {
    self.fbb_.push_slot::<bool>(AlertConfig::VT_ACTIVE, active, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AlertConfigBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AlertConfigBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<AlertConfig<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for AlertConfig<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("AlertConfig");
      ds.field("alert_id", &self.alert_id());
      ds.field("symbol", &self.symbol());
      ds.field("condition_type", &self.condition_type());
      ds.field("threshold", &self.threshold());
      ds.field("active", &self.active());
      ds.finish()
  }
}
pub enum RPCRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RPCRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RPCRequest<'a> {
  type Inner = RPCRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RPCRequest<'a> {
  pub const VT_REQUEST_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_COMMAND: ::flatbuffers::VOffsetT = 6;
  pub const VT_SYMBOL: ::flatbuffers::VOffsetT = 8;
  pub const VT_REPLAY_CONFIG: ::flatbuffers::VOffsetT = 10;
  pub const VT_SUBSCRIPTION: ::flatbuffers::VOffsetT = 12;
  pub const VT_ALERT_CONFIG: ::flatbuffers::VOffsetT = 14;
  pub const VT_SEEK_TIMESTAMP: ::flatbuffers::VOffsetT = 16;
  pub const VT_SPEED_MULTIPLIER: ::flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RPCRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RPCRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RPCRequest<'bldr>> {
    let mut builder = RPCRequestBuilder::new(_fbb);
    builder.add_seek_timestamp(args.seek_timestamp);
    builder.add_speed_multiplier(args.speed_multiplier);
    if let Some(x) = args.alert_config { builder.add_alert_config(x); }
    if let Some(x) = args.subscription { builder.add_subscription(x); }
    if let Some(x) = args.replay_config { builder.add_replay_config(x); }
    if let Some(x) = args.symbol { builder.add_symbol(x); }
    if let Some(x) = args.request_id { builder.add_request_id(x); }
    builder.add_command(args.command);
    builder.finish()
  }


  #[inline]
  pub fn request_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RPCRequest::VT_REQUEST_ID, None)}
  }
  #[inline]
  pub fn command(&self) -> CommandType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<CommandType>(RPCRequest::VT_COMMAND, Some(CommandType::Subscribe)).unwrap()}
  }
  #[inline]
  pub fn symbol(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RPCRequest::VT_SYMBOL, None)}
  }
  #[inline]
  pub fn replay_config(&self) -> Option<ReplayConfig<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReplayConfig>>(RPCRequest::VT_REPLAY_CONFIG, None)}
  }
  #[inline]
  pub fn subscription(&self) -> Option<SubscriptionPayload<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<SubscriptionPayload>>(RPCRequest::VT_SUBSCRIPTION, None)}
  }
  #[inline]
  pub fn alert_config(&self) -> Option<AlertConfig<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<AlertConfig>>(RPCRequest::VT_ALERT_CONFIG, None)}
  }
  #[inline]
  pub fn seek_timestamp(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(RPCRequest::VT_SEEK_TIMESTAMP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn speed_multiplier(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(RPCRequest::VT_SPEED_MULTIPLIER, Some(0.0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for RPCRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("request_id", Self::VT_REQUEST_ID, false)?
     .visit_field::<CommandType>("command", Self::VT_COMMAND, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("symbol", Self::VT_SYMBOL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReplayConfig>>("replay_config", Self::VT_REPLAY_CONFIG, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<SubscriptionPayload>>("subscription", Self::VT_SUBSCRIPTION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<AlertConfig>>("alert_config", Self::VT_ALERT_CONFIG, false)?
     .visit_field::<i64>("seek_timestamp", Self::VT_SEEK_TIMESTAMP, false)?
     .visit_field::<f32>("speed_multiplier", Self::VT_SPEED_MULTIPLIER, false)?
     .finish();
    Ok(())
  }
}
pub struct RPCRequestArgs<'a> {
    pub request_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub command: CommandType,
    pub symbol: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub replay_config: Option<::flatbuffers::WIPOffset<ReplayConfig<'a>>>,
    pub subscription: Option<::flatbuffers::WIPOffset<SubscriptionPayload<'a>>>,
    pub alert_config: Option<::flatbuffers::WIPOffset<AlertConfig<'a>>>,
    pub seek_timestamp: i64,
    pub speed_multiplier: f32,
}
impl<'a> Default for RPCRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    RPCRequestArgs {
      request_id: None,
      command: CommandType::Subscribe,
      symbol: None,
      replay_config: None,
      subscription: None,
      alert_config: None,
      seek_timestamp: 0,
      speed_multiplier: 0.0,
    }
  }
}

pub struct RPCRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RPCRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_request_id(&mut self, request_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RPCRequest::VT_REQUEST_ID, request_id);
  }
  #[inline]
  pub fn add_command(&mut self, command: CommandType) {
    self.fbb_.push_slot::<CommandType>(RPCRequest::VT_COMMAND, command, CommandType::Subscribe);
  }
  #[inline]
  pub fn add_symbol(&mut self, symbol: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RPCRequest::VT_SYMBOL, symbol);
  }
  #[inline]
  pub fn add_replay_config(&mut self, replay_config: ::flatbuffers::WIPOffset<ReplayConfig<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReplayConfig>>(RPCRequest::VT_REPLAY_CONFIG, replay_config);
  }
  #[inline]
  pub fn add_subscription(&mut self, subscription: ::flatbuffers::WIPOffset<SubscriptionPayload<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<SubscriptionPayload>>(RPCRequest::VT_SUBSCRIPTION, subscription);
  }
  #[inline]
  pub fn add_alert_config(&mut self, alert_config: ::flatbuffers::WIPOffset<AlertConfig<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<AlertConfig>>(RPCRequest::VT_ALERT_CONFIG, alert_config);
  }
  #[inline]
  pub fn add_seek_timestamp(&mut self, seek_timestamp: i64) {
    self.fbb_.push_slot::<i64>(RPCRequest::VT_SEEK_TIMESTAMP, seek_timestamp, 0);
  }
  #[inline]
  pub fn add_speed_multiplier(&mut self, speed_multiplier: f32) {
    self.fbb_.push_slot::<f32>(RPCRequest::VT_SPEED_MULTIPLIER, speed_multiplier, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RPCRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RPCRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RPCRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RPCRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RPCRequest");
      ds.field("request_id", &self.request_id());
      ds.field("command", &self.command());
      ds.field("symbol", &self.symbol());
      ds.field("replay_config", &self.replay_config());
      ds.field("subscription", &self.subscription());
      ds.field("alert_config", &self.alert_config());
      ds.field("seek_timestamp", &self.seek_timestamp());
      ds.field("speed_multiplier", &self.speed_multiplier());
      ds.finish()
  }
}
pub enum RPCResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RPCResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RPCResponse<'a> {
  type Inner = RPCResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RPCResponse<'a> {
  pub const VT_REQUEST_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_SUCCESS: ::flatbuffers::VOffsetT = 6;
  pub const VT_ERROR_MESSAGE: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RPCResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RPCResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RPCResponse<'bldr>> {
    let mut builder = RPCResponseBuilder::new(_fbb);
    if let Some(x) = args.error_message { builder.add_error_message(x); }
    if let Some(x) = args.request_id { builder.add_request_id(x); }
    builder.add_success(args.success);
    builder.finish()
  }


  #[inline]
  pub fn request_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RPCResponse::VT_REQUEST_ID, None)}
  }
  #[inline]
  pub fn success(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(RPCResponse::VT_SUCCESS, Some(false)).unwrap()}
  }
  #[inline]
  pub fn error_message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RPCResponse::VT_ERROR_MESSAGE, None)}
  }
}

impl ::flatbuffers::Verifiable for RPCResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("request_id", Self::VT_REQUEST_ID, false)?
     .visit_field::<bool>("success", Self::VT_SUCCESS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("error_message", Self::VT_ERROR_MESSAGE, false)?
     .finish();
    Ok(())
  }
}
pub struct RPCResponseArgs<'a> {
    pub request_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub success: bool,
    pub error_message: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for RPCResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    RPCResponseArgs {
      request_id: None,
      success: false,
      error_message: None,
    }
  }
}

pub struct RPCResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RPCResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_request_id(&mut self, request_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RPCResponse::VT_REQUEST_ID, request_id);
  }
  #[inline]
  pub fn add_success(&mut self, success: bool) {
    self.fbb_.push_slot::<bool>(RPCResponse::VT_SUCCESS, success, false);
  }
  #[inline]
  pub fn add_error_message(&mut self, error_message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RPCResponse::VT_ERROR_MESSAGE, error_message);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RPCResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RPCResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RPCResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RPCResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RPCResponse");
      ds.field("request_id", &self.request_id());
      ds.field("success", &self.success());
      ds.field("error_message", &self.error_message());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `RPCRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rpcrequest_unchecked`.
pub fn root_as_rpcrequest(buf: &[u8]) -> Result<RPCRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<RPCRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `RPCRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_rpcrequest_unchecked`.
pub fn size_prefixed_root_as_rpcrequest(buf: &[u8]) -> Result<RPCRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<RPCRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `RPCRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rpcrequest_unchecked`.
pub fn root_as_rpcrequest_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RPCRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<RPCRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `RPCRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rpcrequest_unchecked`.
pub fn size_prefixed_root_as_rpcrequest_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RPCRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<RPCRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a RPCRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `RPCRequest`.
pub unsafe fn root_as_rpcrequest_unchecked(buf: &[u8]) -> RPCRequest<'_> {
  unsafe { ::flatbuffers::root_unchecked::<RPCRequest>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed RPCRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `RPCRequest`.
pub unsafe fn size_prefixed_root_as_rpcrequest_unchecked(buf: &[u8]) -> RPCRequest<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<RPCRequest>(buf) }
}
#[inline]
pub fn finish_rpcrequest_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<RPCRequest<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_rpcrequest_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<RPCRequest<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Protocol
}  // pub mod NexusQuant

